#define DEFAULT         0
#define PHASE1          100
#define PHASE2          200
#define PHASE3          300
#define PHASE4          400
#define PHASE1OUTPUT    "_phase1.trad"
#define PHASE2OUTPUT    "_phase2.trad"
#define PHASE3OUTPUT    "_phase3.trad"
#define PHASE4OUTPUT    "_md2tex.tex"

#define MAX_COLUMNS     100
#define MAX_NUMBERS     20
#define MAX_FILENAME    100

#define VERBATIM        1
#define HTML            2
#define H1              3
#define H2              4
#define H3              5
#define H4              6
#define H5              7
#define H6              8
#define H1SETEXT        9
#define H2SETEXT        10
#define LINE            11
#define IMAGE           12
#define TABLE           13
#define BULLIST         14
#define NUMLIST         15
#define BLOCKQUOTE      16
#define INDENT          17
#define CODEBLOCK       18
#define CODEINLINE      19
#define STRONG          20
#define EMPH            21
#define STRONGEMPH      22
#define STRIKETHROUGH   23
#define LINK            24

#define ESCAPEBS        "\\\\ESCAPE\\|\\\\"
#define ESCAPEBT        "\\\\ESCAPE\\`\\\\"
#define ESCAPEAS        "\\\\ESCAPE\\*\\\\"
#define ESCAPEUN        "\\\\ESCAPE\\_\\\\"
#define ESCAPECU1       "\\\\ESCAPE\\{\\\\"
#define ESCAPECU2       "\\\\ESCAPE\\}\\\\"
#define ESCAPESB1       "\\\\ESCAPE\\[\\\\"
#define ESCAPESB2       "\\\\ESCAPE\\]\\\\"
#define ESCAPEPA1       "\\\\ESCAPE\\(\\\\"
#define ESCAPEPA2       "\\\\ESCAPE\\)\\\\"
#define ESCAPEHA        "\\\\ESCAPE\\#\\\\"
#define ESCAPEPL        "\\\\ESCAPE\\+\\\\"
#define ESCAPEMI        "\\\\ESCAPE\\-\\\\"
#define ESCAPEDO        "\\\\ESCAPE\\.\\\\"
#define ESCAPEEX        "\\\\ESCAPE\\!\\\\"